const messages={
  configuration_required:'A ESJ ainda precisa configurar o servidor, o banco e o aplicativo Meta para liberar esta conexão.',
  invalid_login:'E-mail ou senha inválidos, ou acesso administrativo indisponível.',
  authentication_required:'Entre com sua conta administrativa da ESJ para continuar.',
  admin_required:'Sua conta não tem permissão administrativa para esta ação.',
  invalid_origin:'Acesse a plataforma pelo endereço HTTPS configurado pela ESJ.',
  rate_limited:'Muitas tentativas. Aguarde antes de tentar novamente.',
  signup_cancelled:'Conexão cancelada. Nenhuma nova autorização foi concluída na ESJ.',
  meta_authorization_cancelled:'A autorização na Meta foi cancelada.',
  signup_timeout:'O fluxo não retornou todos os dados necessários. Inicie uma nova tentativa.',
  sdk_unavailable:'Não foi possível carregar ou abrir a Meta. Verifique bloqueadores e tente novamente.',
  network_error:'Não foi possível confirmar o resultado. Atualize o status antes de repetir a ação.',
  reauthorization_required:'A Meta exige uma nova autorização para esta conta.',
  invalid_token:'A credencial retornada pela Meta não pôde ser validada. Autorize novamente.',
  missing_permissions:'A autorização não inclui todas as permissões necessárias.',
  invalid_waba:'A conta WhatsApp selecionada não pertence aos ativos autorizados.',
  invalid_business:'Não foi possível confirmar a empresa proprietária da conta WhatsApp.',
  invalid_phone_number:'O número selecionado não foi encontrado na conta WhatsApp autorizada.',
  invalid_state:'A tentativa expirou, já foi utilizada ou não pertence à sua sessão. Inicie novamente.',
  asset_already_connected:'Este ativo já está vinculado a outra empresa na plataforma.',
  message_outcome_unknown:'Não foi possível confirmar o envio. Para evitar duplicidade, não reenvie: confira o destinatário e os registros antes de iniciar outro teste.',
  template_not_supported:'Selecione um template aprovado, somente de texto e sem parâmetros ou botões.',
  registration_failed:'A Meta não confirmou o registro do número. Confira a configuração e use “Validar novamente”.',
};
export function errorMessage(error){return messages[error.code || error.message] || 'A operação não foi concluída. Verifique a configuração ou contate a ESJ.';}
